### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by trpstra** [Extreme-classification/ECLARE#3]
Hi,

I am trying to apply your method to my dataset, and attempting to figure out the format of the input data from reading the code and looking at the example datasets (LF-AmazonTitles-131K). Some documentation for this would be greatly appreciated, but I can mostly figure it out. Only the `filter_labels_train.txt` and `filter_labels_test.txt` matrices are not clear to me. If you could briefly explain what these matrices are and why they are needed, that would be great.

Thanks in advance!

**Comment by anshumitts** [comment]
Hi @onclue, These files consist of **doc_ids-space-label_ids** of reciprocal pairs in the datasets. I would recommend reading through [XML repo](http://manikvarma.org/downloads/XC/XMLRepository.html). It has detailed points on every file. 
We filter out these pairs during evaluation so that methods that exploit meta-data cannot get trivial gains in the evaluation metric to have a fair comparison.
-AM
